version: "3.9"

services:
  service_a:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "src.service_a.app:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  service_b:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "src.service_b.app:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  redis:
    image: redis:6.2
    container_name: message_queue_redis
    ports:
      - "6379:6379"

