REDIS_MESSAGE_QUEUE_NAME = "message_queue"
REDIS_CONNECTION_URL = "redis://redis:6379"
REDIS_MAX_RETRIES = 2
REDIS_RETRY_DELAY_SECONDS = 2
REDIS_MESSAGE_QUEUE_MAX_SIZE = 10
REDIS_MESSAGE_SUBSCRIBE_TIMEOUT_SECONDS = 5

WEBSOCKET_POLL_INTERVAL_SECONDS = 2

MESSAGE_MAX_CONTENT_LENGTH = 256
MESSAGE_FILTER_MODE = "allow_all"