REDIS_QUEUE_NAME="message_queue"
REDIS_URL="redis://redis:6379"
REDIS_RETRY_COUNT=2
REDIS_RETRY_SLEEP_SEC=2
REDIS_QUEUE_MAX_SIZE = 10
REDIS_SUBSCRIBE_TIMEOUT=5

WEBSOCKET_SLEEP_SEC=2

MAX_MESSAGE_LENGTH=256
MESSAGE_FILTER_TYPE="allow_all"